# -*- coding: utf-8 -*-
"""Default - 100 Epochs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZSf9KiYxbNd8uo4lPh5wsAEc2mleIY8
"""

# Install ucimlrepo (run this cell once)
!pip install ucimlrepo

# Commented out IPython magic to ensure Python compatibility.
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from ucimlrepo import fetch_ucirepo
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# Enable inline plotting for Jupyter
# %matplotlib inline

# Fetch the dataset from UCI
wine_quality = fetch_ucirepo(id=186)

# Extract features (X) and target (y)
X = wine_quality.data.features
y = wine_quality.data.targets

# Display basic info
print("Dataset shape:", X.shape)
print("Features:", list(X.columns))
print("Target shape:", y.shape)
print("Sample data:")
print(X.head())
print("Target sample:")
print(y.head())

# Summary statistics
print("Feature statistics:")
print(X.describe())

# Target distribution
print("\nTarget (Quality) distribution:")
print(y['quality'].value_counts().sort_index())

# Visualize feature distributions
X.hist(figsize=(12, 10), bins=20)
plt.suptitle("Feature Distributions")
plt.show()

# Visualize target distribution
plt.figure(figsize=(8, 6))
sns.countplot(x=y['quality'])
plt.title("Quality Score Distribution")
plt.xlabel("Quality Score")
plt.ylabel("Count")
plt.show()

# Initialize scaler
scaler = StandardScaler()

# Fit and transform features
X_scaled = scaler.fit_transform(X)

# Convert back to DataFrame for consistency
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

print("Scaled features sample:")
print(X_scaled.head())

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print("Train set shape:", X_train.shape, y_train.shape)
print("Test set shape:", X_test.shape, y_test.shape)

# Build the model
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(32, activation='relu'),
    layers.Dense(1)  # No activation for regression
])

# Model summary
model.summary()

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])  # MAE as additional metric

# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test), verbose=1)

# Predict on test set
y_pred = model.predict(X_test)

# Calculate MSE
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error on Test Set: {mse:.4f}")

# Visualize predictions vs. actual
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel("Actual Quality")
plt.ylabel("Predicted Quality")
plt.title("Predictions vs. Actual Quality")
plt.show()

# Optional: Plot training history
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss Over Epochs')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['mae'], label='Train MAE')
plt.plot(history.history['val_mae'], label='Val MAE')
plt.title('MAE Over Epochs')
plt.legend()
plt.show()